name: Lint & Tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install poetry
        run: pip install poetry poetry-core
      - name: Install dependencies
        run: poetry install
      - name: Run linters & friends
        run: make lint

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install poetry
        run: pip install poetry poetry-core
      - name: Install dependencies
        run: poetry install
      - name: Set credentials
        run: echo "$PYTHON_CREDS_FILE" > ${GITHUB_WORKSPACE}/main/creds.py
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/main" >> $GITHUB_ENV
      - name: Run tests, with coverage testing
        run: poetry run pytest --cov=main --cov-report=term-missing main
